name: Test
on: [push]
jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd $GITHUB_WORKSPACE
          pip install sacrebleu
      - name: Run Tests
        run: python -m unittest tests/*.py
